version: 2
jobs:
  build:
    docker: #执行容器
      - image: circleci/node:10 #依赖环境
    branches: #分支
      only:
      - master
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - add_ssh_keys:
          fingerprints:
            - '93:15:5f:ea:5c:27:23:a8:05:30:26:d1:57:16:64:9b'
      - checkout # 从githun拉去代码
      # 使用缓存
      - restore_cache:
          key: node-dependens
      - run: 
          name: Install
          command: yarn install
      # 设置缓存
      - save_cache:
          key: node-dependens
          paths:
            - node_modules
      - run:
          name: Build
          command: yarn build
      - run:
          name: shell auth
          command: chmod +x scripts/deploy.sh
      - run:
          name: Deploy
          command: ./scripts/deploy.sh